name: rse
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.11
  http: ^0.13.6
  syncfusion_flutter_charts: ^21.2.9
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.0.9
  intl: ^0.18.0
  flutter_chart: ^0.1.6
  bloc: ^8.1.2
  collection: ^1.17.1
  flutter_dotenv: ^5.1.0
  go_router: ^8.0.5
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  device_info_plus: ^9.0.2
  faker: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/


